### PR TITLE
Fix CI: fix compilation error due to incorrect PeerMetadata import

### PR DESCRIPTION
**Pull request by timvisee**
CI on dev is currently failing.

This compilation error slipped through somehow. Maybe due to a bad merge or a stacked PR.

In any case, this resolve the problem.

### All Submissions:

* [x] Contributions should target the `dev` branch. Did you create your branch from `dev`?
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?

### New Feature Submissions:

1. [x] Does your submission pass tests?
2. [x] Have you formatted your code locally using `cargo +nightly fmt --all` command prior to submission?
3. [x] Have you checked your code using `cargo clippy --all --all-features` command?

### CODE REVIEW

**Review by agourlay — APPROVED** [review]
:ship:
